# Site settings
title: John P Gallagher
email: jpgallagher@gmail.com
description: test test abc # this means to ignore newlines until "baseurl:"
baseurl: "home" # the subpath of your site, e.g. /blog/
url: "jpgallagher1.github.io" # the base hostname & protocol for your site

twitter_username: JohnPGallagher7
github_username: jpgallagher1
linkedin_url: john-gallagher-7348b163

# Build settings
markdown: kramdown
